name: Deploy to Staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to Staging Cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH into the ec2 server
        run: |
          echo "${{ secrets.RSA_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts 
          echo "${{ secrets.KNOWN_HOSTS }}" &> ~/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key ubuntu@3.88.137.128 -t "cd cohort-3-bms/ && git pull && pnpm install && pnpm run build && pm2 restart http-server && pm2 restart ws-server && pm2 restart web"
